## Setup
Die folgenden Module werdet Ihr fast immer gebrauchen: 

In [2]:
import numpy as np
import matplotlib.pyplot as plt

Die folgenden Methoden verwenden wir oft, um Vektoren und Matrizen zu generieren (j ist die imaginäre Konstante). `dtype=complex` lässt sich bei all diesen verwenden. 

In [20]:
a = np.zeros((4, 6)) 
print(f"Alles nullen:\n{a}")

b = np.ones((6, 1), dtype=complex)
print(f"Alles einsen (komplex, vertikaler Vektor):\n{b}")

c = np.array([              
    [5 + 7j, 6, 7],
    [8, 9, 0]
])
print(f"2D-Array zum Erstellen einer Matrix:\n{c}")

d = np.arange(6)
print(f"Integers von 0 bis 5:\n{d}")

e = np.linspace(0, 1, 4)
print(f"200 äquidistante Punkte zwischen 0 und 1:\n{e}")

Alles nullen:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Alles einsen (komplex, vertikaler Vektor):
[[1.+0.j]
 [1.+0.j]
 [1.+0.j]
 [1.+0.j]
 [1.+0.j]
 [1.+0.j]]
2D-Array zum Erstellen einer Matrix:
[[5.+7.j 6.+0.j 7.+0.j]
 [8.+0.j 9.+0.j 0.+0.j]]
Integers von 0 bis 5:
[0 1 2 3 4 5]
200 äquidistante Punkte zwischen 0 und 1:
[0.         0.33333333 0.66666667 1.        ]


## Operationen
Um Elemente eines Vektors zu setzen, gibt es folgende Notationen:

In [21]:
# Ein Element setzen (n argumente für n dimensionen)
a[3, 3] = 1 
a[:, 2] = 2        # ':'  setzt alle elemente in dieser dimension
a[1, :2] = 3       # ':x' setzt alle  Elemente bis zum x-ten
a[2:, 4:] = 4      # 'y:' setzt alle nach einem index (kombinierbar zu 'y:x')
a[0, :4] = d[:4]   # Wir können einen ganzen Vektor als Teil einer Matrix einfügen

# Ganze sub-matrizen können zugewiesen werden. 
a[2:4, 0:2] = np.ones((2, 2))

print(a)

[[0. 1. 2. 3. 0. 0.]
 [3. 3. 2. 0. 0. 0.]
 [1. 1. 2. 0. 4. 4.]
 [1. 1. 2. 1. 4. 4.]]


Das Symbol für eine Matrix-Multiplikation ist `@`, und Transposition ist das attribut `T`:

In [22]:
print(a @ b)

[[ 6.+0.j]
 [ 8.+0.j]
 [12.+0.j]
 [13.+0.j]]


In [14]:
print(c.T)

[[5 8]
 [6 9]
 [7 0]]


Numpy hat die meisten wichtigen mathematischen Funktionen. Diese lassen sich auf ganze Vektoren komponentenweise anwenden:

In [23]:
f = np.exp
print(f(d))

[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


Auch die arithmetischen Operationen aus python lassen sich komponentenweise anwenden:

In [25]:
print(b+1)
print(5**d)

[[2.+0.j]
 [2.+0.j]
 [2.+0.j]
 [2.+0.j]
 [2.+0.j]
 [2.+0.j]]
[   1    5   25  125  625 3125]


Wenn die Dimensionen von Vektoren übereinstimmen, passiert die Operation direkt komponentenweise.
Hier berechnen wir $x + \sqrt{x}$ für alle Komponenten:

In [26]:
print(d + np.sqrt(d))

[0.         2.         3.41421356 4.73205081 6.         7.23606798]


Wenn eine Dimension in einem Vektor $1$ ist, und im anderen $n$, dann wird die eindimensionale Komponente auf alle $n$ Zeilen/Spalten angewendet:

In [28]:
print(d ** np.array([e]).T)

[[1.         1.         1.         1.         1.         1.        ]
 [0.         1.         1.25992105 1.44224957 1.58740105 1.70997595]
 [0.         1.         1.58740105 2.08008382 2.5198421  2.92401774]
 [0.         1.         2.         3.         4.         5.        ]]


Hier ist der Exponent (rechts) senkrecht, und d waagrecht, deswegen zeigt die Matrix jede komponente in $d$ (Zeile) hoch jede Komponente in $e^T$ (Spalte):

$[{d_i}^{e_j}]_{i=0, j=0}^{n, m}$